server:
  port: 8000

#eureka:
#  client:
#    fetch-registry: true # 유레카 클라이언트 활성화
#    register-with-eureka: true # 유레카 클라이언트 활성화
#    service-url:
#      defaultZone: http://localhost:8761/eureka # 유레카 클라이언트로 등록

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
#        - id: product-service
#          #uri: http://localhost:8082 # 포워딩할 주소, http://localhost:8000/user 로 들어오면 http://localhost:64412 로 포워딩
#          uri: lb://PRODUCT-SERVICE
#          predicates:
#           - Path=/** # 해당 gateway 서버의 /product/**로 들어오는 요은 product-service로 인식하겠다는 조건
#
#        - id: shop-service
#          #uri: http://localhost:8081
#          uri: lb://SHOP-SERVICE
#          predicates:
#            - Path=/**
        - id: content
          uri: http://localhost:8090
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: ["health", "refresh"]